name: check_licenses
permissions:
  contents: read
jobs:
  check_licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    env:
      BUILD_TASK: check_licenses
      GITHUB: 'true'
      LOG_DIR: ${{ github.workspace }}/tmp/var/log
      LOG_FILE_BUILD_TASK: ${{ github.workspace }}/tmp/var/log/check_licenses.log
      LOG_NUM_LINES: 5000
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        clean: false
        fetch-depth: 100
        lfs: false
      timeout-minutes: 10
    - name: Initialize log files
      run: |
        mkdir -p "${{ env.LOG_DIR }}"
        touch "${{ env.LOG_FILE_BUILD_TASK }}"
      timeout-minutes: 2
    - name: Install Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
      with:
        node-version: '20'
      timeout-minutes: 5
    - name: Print debug info
      run: |
        echo 'PATH:'
        echo $PATH
        echo ''
        echo 'Git:'
        git --version
        echo ''
        echo 'Node.js:'
        file $(which node)
        node --version
        node -p 'process.platform + "@" + process.arch'
        echo ''
        echo 'npm:'
        npm --version
        npm config get registry
      timeout-minutes: 2
    - name: Perform install sequence
      run: |
        make install-node-modules || make install-node-modules || make install-node-modules
      timeout-minutes: 30
    - name: Run build task
      run: |
        . "$GITHUB_WORKSPACE/.github/workflows/scripts/common/task_runner" "${{ env.BUILD_TASK }}" "${{ env.LOG_FILE_BUILD_TASK }}"
      timeout-minutes: 360
    - name: View log file
      if: failure()
      run: |
        echo "Printing the last ${{ env.LOG_NUM_LINES }} lines of log output..."
        tail -${{ env.LOG_NUM_LINES }} "${{ env.LOG_FILE_BUILD_TASK }}"
      timeout-minutes: 5
    - name: Upload log file
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      if: always()
      with:
        name: ${{ env.BUILD_TASK }}_log
        path: ${{ env.LOG_FILE_BUILD_TASK }}
        retention-days: 14
      timeout-minutes: 10
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
- pull_request
